### ISSUE TITLE
Support for multi-root workspaces (when you have >1 git repo in your explorer view)

### ISSUE THREAD

**Issue by white-hat** [morrislaptop/vscode-open-in-sourcetree#1]
Currently in a multi-root workspace SourceTree always opens the folder which was added first. When using "Open in SourceTree" context menu against a folder, I want to be able to open SourceTree with workdir set to this folder, not the project root folder.
As I understand, as a hack I should change https://github.com/morrislaptop/vscode-open-in-sourcetree/blob/master/extension.js#L5 to something like
```javascript
    const { rootPath } = vscode.filepath
```
But i'm not sure

**Comment by morrislaptop** [comment]
Will take a PR :)

**Comment by kachkaev** [comment]
That'd be a great feature to have! Was using it the in atom's [open-in-sourcetree](https://github.com/cliffrowley/atom-open-in-sourcetree) plugin before looking towards vscode.

What'd be also useful is to set up a dropdown with all project paths in workspace and let users choose a repo from there (e.g. by filtering with a few keys and pressing enter). When working with multiple projects, it is not always the case that the repo you want to see is the same as the file that's currently open.

**Comment by morrislaptop** [comment]
Fixed with 8ad94039a042ed220f6c6f28a094158f56a32c68
