### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Leon99** [morrislaptop/vscode-open-in-sourcetree#2]
Only gives "command 'openInSourceTree.open' not found" error.

**Comment by kachkaev** [comment]
@Leon99 what is your issue exactly and what does your environment look like? I just installed `open-in-sourcetree` for the latest vscode on macos and all worked. The only issue I have is https://github.com/morrislaptop/vscode-open-in-sourcetree/issues/1.

**Comment by Leon99** [comment]
Latest stable Win10, latest stable VSCode, latest SourceTree.
