### ISSUE TITLE
Indicate in documentation that SourceTree must be in PATH

### ISSUE THREAD

**Issue by Riduidel** [morrislaptop/vscode-open-in-sourcetree#5]
Seems like this extension requires `SourceTree` command to be in system PATH.
As it is not stated in documentation, this lead to "Windows doesn't find SourceTree" error dialog ... frustrating.

**Comment by morrislaptop** [comment]
@Riduidel I've swapped libraries to open the app which seems to be better in windows. Could you check?

**Comment by gsabater** [comment]
Hi @morrislaptop 

I have installed the extension today, and I get the same `Windows doesn't find SourceTree` error in windows as well.

If you could provide indications about how to put sourcetree in PATH would be nice.
